receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  # Traces -> Tempo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Logs -> Loki (minimal config to avoid schema mismatches)
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Metrics -> Mimir via Prometheus Remote Write
  prometheusremotewrite/mimir:
    endpoint: http://mimir:9009/api/v1/push

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/mimir]